CREATE DATABASE Test_PowerLine
COLLATE Cyrillic_General_CI_AS
GO

USE Test_PowerLine
GO

CREATE TABLE CUSTOMERS
(
	CUSTOMER_ID int NOT NULL IDENTITY PRIMARY KEY, 
	NAME nvarchar(100)	
)
GO

CREATE TABLE ORDERS
(
	ORDER_ID int NOT NULL IDENTITY PRIMARY KEY,
	CUSTOMER_ID int FOREIGN KEY REFERENCES CUSTOMERS (CUSTOMER_ID) ON DELETE SET NULL	
)
GO

INSERT INTO CUSTOMERS([NAME]) VALUES
('Max'), ('Pavel'), ('Ivan'), ('Leonid')
GO

INSERT INTO ORDERS(CUSTOMER_ID) VALUES
('2'), ('4')
GO

SELECT C.NAME FROM CUSTOMERS AS C
WHERE C.CUSTOMER_ID NOT IN(
SELECT C.CUSTOMER_ID FROM CUSTOMERS AS C
JOIN ORDERS AS O ON O.CUSTOMER_ID = C.CUSTOMER_ID)